[package]
name = "drone-sitl"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow     = { workspace = true }
thiserror  = { workspace = true }
serde      = { workspace = true }
toml       = { workspace = true }
drone-model   = { path = "../drone-model" }
drone-sim     = { path = "../drone-sim" }
drone-control = { path = "../drone-control" }
nalgebra   = { workspace = true }
rand       = { workspace = true }
rand_distr = { workspace = true }
rayon      = { workspace = true }
